### ISSUE TITLE
Fails to Load on XFCE

### ISSUE THREAD

**Issue by crutchcorn** [liri-project/liri-browser#172] opened 2015-11-30 18:10 UTC
Upon installing liri-browser-git from AUR, I get this error running from command line

```bash
[crutchcorn@testing ~]$ liri-browser 
Couldn't open config file.
qml: Locale name: en_US
qrc:/qml/BaseApplication.qml:246: TypeError: Cannot read property 'length' of undefined
qrc:/qml/BrowserTabBar.qml:20:5: QML ListView: Binding loop detected for property "width"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "minimumWidth"
qrc:/qml/FullscreenBar.qml:30:9: QML Image: Cannot open: qrc:/qml/action/dashboard
qrc:/qml/TabBarItemDelegate.qml:98:21: QML Image: Cannot open: qrc:/qml/action/dashboard
file:///usr/lib/qt/qml/QtQuick/Controls/Styles/Material/TextFieldStyle.qml:35: ReferenceError: echoMode is not defined
qrc:/qml/RightDrawer.qml:30:15: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/Omnibox.qml:130:20: Unable to assign [undefined] to QColor
qrc:/qml/Omnibox.qml:214:20: Unable to assign [undefined] to QColor
qrc:/qml/BrowserPage.qml:247:20: Unable to assign [undefined] to QColor
qrc:/qml/RightDrawer.qml:30:15: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
qrc:/qml/RightDrawer.qml:30:15: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
qrc:/qml/BrowserPage.qml:346:16: Unable to assign bool to QColor
qrc:/qml/Settings.qml:450:35: Unable to assign double to QQuickAnchorLine
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
file:///usr/lib/qt/qml/QtQuick/Controls/Styles/Material/TextFieldStyle.qml:35: ReferenceError: echoMode is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
file:///usr/lib/qt/qml/QtQuick/Controls/Styles/Material/TextFieldStyle.qml:35: ReferenceError: echoMode is not defined
Loading plugins
Loading plugin "cdm" "/home/crutchcorn/cdm"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Desktop" "/home/crutchcorn/Desktop"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Documents" "/home/crutchcorn/Documents"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Downloads" "/home/crutchcorn/Downloads"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "material" "/home/crutchcorn/material"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Music" "/home/crutchcorn/Music"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Pictures" "/home/crutchcorn/Pictures"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Public" "/home/crutchcorn/Public"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "qml" "/home/crutchcorn/qml"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Templates" "/home/crutchcorn/Templates"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Videos" "/home/crutchcorn/Videos"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Triggered event "load"
Segmentation fault (core dumped)
```

**Comment by tim-sueberkrueb** [comment] 2015-12-02 11:00
@crutchcorn this is a duplicate of #170. Right issue this time ^^

**Closed by tim-sueberkrueb** 2015-12-02 11:00 UTC
Labels: duplicate

**Comment by crutchcorn** [comment] 2015-12-02 16:38
My bad @tim-sueberkrueb, I saw that issue but couldn't tell if that bug was the same or not. :/

**Comment by tim-sueberkrueb** [comment] 2015-12-03 10:50
@crutchcorn no problem at all :) better report it in case of doubt :+1:
